services:
  - type: web
    name: igris-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: igris-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://frontend-topaz-pi-51.vercel.app"

databases:
  - name: igris-db
    plan: free
